name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-macos:
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v # --enable-code-coverage
    # - name: Generate lcov report
    #   run: xcrun llvm-cov export -format="lcov" .build/debug/cgtcalcPackageTests.xctest/Contents/MacOS/cgtcalcPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    # - name: Upload code coverage
    #   uses: codecov/codecov-action@v2.1.0

  test-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Swift
      uses: fwal/setup-swift@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
